vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
      type: attribute

    mappings:
      user_image:
        uri_prefix: /images/users
        upload_destination: user.storage
        namer: Vich\UploaderBundle\Naming\UniqidNamer
        delete_on_update: true
        delete_on_remove: true
      energy_stations_image:
        uri_prefix: /images/energy_stations
        upload_destination: energy_stations.storage
        namer: Vich\UploaderBundle\Naming\UniqidNamer
        delete_on_update: true
        delete_on_remove: true
      energy_stations_brand_image:
        uri_prefix: /images/energy_stations_brand
        upload_destination: energy_stations_brand.storage
        namer: Vich\UploaderBundle\Naming\UniqidNamer
        delete_on_update: true
        delete_on_remove: true
      energy_types_image:
        uri_prefix: /images/energy_types
        upload_destination: energy_types.storage
        namer: Vich\UploaderBundle\Naming\UniqidNamer
        delete_on_update: true
        delete_on_remove: true
