parameters:
  gasUrl: "%env(GAS_URL)%"
  gasPath: "%env(GAS_PATH)%"
  gasName: "%env(GAS_NAME)%"
  gasJsonName: "%env(GAS_JSON_NAME)%"
  evPath: "%env(EV_PATH)%"
  evJsonName: "%env(EV_JSON_NAME)%"
  evUrl: "%env(EV_URL)%"
  positionStackApiKey: "%env(POSITION_STACK_API_KEY)%"
  positionStackUrl: "%env(POSITION_STACK_URL)%"
  googleApiKey: "%env(GOOGLE_API_KEY)%"
  placeTextsearchUrl: "%env(PLACE_TEXTSEARCH_URL)%"
  placeDetailsUrl: "%env(PLACE_DETAILS_URL)%"
  latitudeDefault: "%env(LATITUDE_DEFAULT)%"
  longitudeDefault: "%env(LONGITUDE_DEFAULT)%"
  radiusDefault: "%env(RADIUS_DEFAULT)%"
  energyTypeUuidDefault: "%env(ENERGY_TYPE_UUID_DEFAULT)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
          string $gasUrl: "%gasUrl%"
          string $gasPath: "%gasPath%"
          string $gasName: "%gasName%"
          string $gasJsonName: "%gasJsonName%"
          string $evJsonName: "%evJsonName%"
          string $evPath: "%evPath%"
          string $evUrl: "%evUrl%"
          string $positionStackApiKey: "%positionStackApiKey%"
          string $positionStackUrl: "%positionStackUrl%"
          string $googleApiKey: "%googleApiKey%"
          string $placeTextsearchUrl: "%placeTextsearchUrl%"
          string $placeDetailsUrl: "%placeDetailsUrl%"
          string $latitudeDefault: "%latitudeDefault%"
          string $longitudeDefault: "%longitudeDefault%"
          string $radiusDefault: "%radiusDefault%"
          string $energyTypeUuidDefault: "%energyTypeUuidDefault%"

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\ApiResource\:
        resource: "../src/ApiResource"
        tags: [ "controller.service_arguments" ]

    App\Decorator\JwtDecorator:
        decorates: "api_platform.openapi.factory"

    App\EventSubscriber\UserSubscriber:
        tags: [ doctrine.event_subscriber ]

    App\EventListener\UserChangedNotifier:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
